#!/bin/sh -x

if [ -d /local/mysql-db-backups/binlogs ]; then
	touch /local/mysql-db-backups/binlogs
	find /local/mysql-db-backups/binlogs/ -type f -mtime +14 -print -exec rm -f {} \;

	mkdir /local/mysql-db-backups/binlogs/dummy$$
	find /local/mysql-db-backups/binlogs/* -depth -type d -exec rmdir {} \; >/dev/null 2>&1
fi