#!/bin/sh -x

mysql <<EOF
set global slow_query_log_file='/local/mysql/slow-queries.log';
set global slow_query_log='ON';
set global long_query_time=2;
set global log_queries_not_using_indexes='ON';
EOF
