#!/usr/bin/perl

my $cpu = `uname -p`;

chdir("tar") || die;

if ( $cpu =~ /x86_64/ ) {
    system( "wget",
        "http://www.percona.com/redir/downloads/Percona-Server-5.5/Percona-Server-5.5.21-25.1/binary/linux/x86_64/Percona-Server-5.5.21-rel25.1-234.Linux.x86_64.tar.gz");
}
else {
    system( "wget",
        "http://www.percona.com/redir/downloads/Percona-Server-5.5/Percona-Server-5.5.21-25.1/binary/linux/i686/Percona-Server-5.5.21-rel25.1-234.Linux.i686.tar.gz" );
}