#!/bin/sh 

PATH=/local/mysql/server/bin:/usr/bin:$PATH

# Replace systemwide client config file
rm -f /etc/my.cnf
cp /local/mysql/client.conf /etc/my.cnf

rm -f /usr/local/mysql

cd /local/mysql/server
./mysql_upgrade --datadir=/local/mysql/data 
