#!/bin/sh -x

cd /local/mysql/server

PATH=/local/mysql/server/bin:/usr/bin:$PATH

/local/mysql/setup-local-dirs $*

# Handle deprecated variable names
perl -pi -e "s/table_cache=/table_open_cache=/go" mysql.conf

/local/mysql/rc.mysqld

sleep 10

if [ -e "/local/mysql/cluster" ]; then
	sleep 10
fi

mysql_upgrade
